### ISSUE TITLE
Can you upload highlighted pdf  in repo for testing purposes

### ISSUE THREAD

**Issue by toome123** [soulisalmed/biff#1]
Maybe this is not the right place to comment this, but I don't see another way to contact you. I want to test the program and improve it, but I don't have remarkable yet. So it will be nice if have one highlighted pdf for testing..

**Comment by soulisalmed** [comment]
I uploaded an example (anwar2009.pdf). The article is in open archive (https://doi.org/10.1016/j.camwa.2009.02.025) so it should not be a problem to have it here.

The pdf was highlighted by somebody that does not know how biff works under the hood, which makes it a good exemple for testing purposes. For example:

- The title does no export in full because it is not fully covered by highlight.
- page 2 : the bounding box made around the contour of highlights implies that more text is exported than was highlighted.
- page 3 : the gaps between first and second line are exported as images (see hierarchy in opencv). that's why I included 2 iterations of dilate followed by 2 iterations of erode, to try to close small gaps. However this leads to closing gaps between distinct lines (for example between the formula and the next line).

I consider that after a few trial, the user understands how biff reacts and can highlight accordingly. And of course it is always possible to erase/correct text/images in the odt file as long as the code minimizes the artifacts.

However if you come up with some solution to make the code more robust, you are most welcomed.

**Comment by toome123** [comment]
That's it. Thanks. The tool is very simple, but have powerful idea. I want to make it more user friendly, because not every one can execute commands. they need some kind of UI. And I thing it's possible to make some kind of linguistic corrections, анд that way is not necessary to be precise when highlighting the text, the script will "auto-correct and select the the whole word, sentence or paragraph"

**Comment by soulisalmed** [comment]
The UI is a good idea of course. As you might have seen on my other repo, I have a Flask that runs on a private server. A desktop UI might be nice to distribute, and is fairly easy to develop. 

The script extract full words. and by words I mean what the pdf considers as "words".
I have a pdf that was generated by character recognition, so letter by letter. In this case for the pdf, each letter is a "word". So the result is awful ;) If you are interested I can send it to you.
Concerning paragraphs, I'd be interested to see the solution you come up with. As far as I know there is no stucture in the pdf for paragraphs easily recognizable.
